name: flutter_movies_app
description: Code Challenge Flutter Movies App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2

  dio: ^5.3.2

  either_dart: ^1.0.0

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

  get_it: ^7.6.0

  jumping_dot: ^0.0.6

  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  sizer: ^2.0.15

  url_launcher: ^6.1.12

  webview_flutter: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
